package com.gistone.seimp.job;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DataServiceService service = new DataServiceService();
 * DataService portType = service.getDataServicePort();
 * portType.getData(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DataServiceService", targetNamespace = "http://geoway.cn/", wsdlLocation = "http://10.240.25.252:8099/Service/DataService?wsdl")
public class DataServiceService extends Service {

	private final static URL DATASERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.gistone.seimp.job.DataServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.gistone.seimp.job.DataServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.240.25.252:8099/Service/DataService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.240.25.252:8099/Service/DataService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DATASERVICESERVICE_WSDL_LOCATION = url;
	}

	public DataServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DataServiceService() {
		super(DATASERVICESERVICE_WSDL_LOCATION, new QName("http://geoway.cn/",
				"DataServiceService"));
	}

	/**
	 * 
	 * @return returns DataService
	 */
	@WebEndpoint(name = "DataServicePort")
	public DataService getDataServicePort() {
		return super.getPort(new QName("http://geoway.cn/", "DataServicePort"),
				DataService.class);
	}

}
